### PR TITLE
Home page and menu changes

### PR DESCRIPTION
**Pull request by BenG-SFDC**

### CODE REVIEW

**Review by pmcintyresfdc — APPROVED** [review]

**Comment by pmcintyresfdc** [comment]
@BenG-SFDC Looks good! You can see it at https://fragforce-org-dj-pr-5.herokuapp.com before merge if you want. Otherwise I'll merge it now.

**Comment by parkervcp** [comment]
@BenG-SFDC Can we nix the button style on the top bar? It has a super old school vibe and is not exactly pleasing to the eye.

Maybe adding a vertical line between buttons to differentiate them.

edit: Also making the buttons the same width.

**Comment by pmcintyresfdc** [comment]
I'm happy with the buttons. But I love Zabbix, so I guess my sense of style is a bit off. :-p

**Comment by AevumDecessus** [comment]
Something is off site pages (this is scrolled all the way to the top)
image

**Comment by BenG-SFDC** [comment]
Note: layout only currently applied to main page.  will need to add padding to sub-pages to accommodate the new sticky menu bar. So ignore any over-scrolled pages for the time being.

Edit: fixed, all pages have proper padding now

**Comment by BenG-SFDC** [comment]
Yeah had no idea how to do that, so i rolled back all those changes.  I say we go forward with this as-is, and I can work on that field separately afterwards, as its not directly related with the visual changes anyway.  Im going to have to pull focus from this till probably the weekend, so lets get what we have moving along 

@gpmidi

**Comment by gpmidi** [comment]
@BenG-SFDC I'll check it out tomorrow if I have time. At worst I'm off all of next week - Can check it out then. :)

**Review by gpmidi — APPROVED** [review]

**Pull request merged**
